"""foo_col and comment

Revision ID: 81ad0f6073ba
Revises: bdade81ccfc4
Create Date: 2025-01-31 17:02:46.889163

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "81ad0f6073ba"
down_revision: Union[str, None] = "bdade81ccfc4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("my_table", sa.Column("foo_col", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("my_table", "foo_col")
    # ### end Alembic commands ###
