"""initial table

Revision ID: bdade81ccfc4
Revises:
Create Date: 2025-01-31 17:00:05.816877

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import databricks


# revision identifiers, used by Alembic.
revision: str = "bdade81ccfc4"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "my_table",
        sa.Column("bigint_col", sa.BigInteger(), nullable=False),
        sa.Column("string_col", sa.String(), nullable=True),
        sa.Column("tinyint_col", databricks.sqlalchemy._types.TINYINT(), nullable=True),
        sa.Column("int_col", sa.Integer(), nullable=True),
        sa.Column("numeric_col", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("boolean_col", sa.Boolean(), nullable=True),
        sa.Column("date_col", sa.Date(), nullable=True),
        sa.Column(
            "datetime_col", databricks.sqlalchemy._types.TIMESTAMP(), nullable=True
        ),
        sa.Column("datetime_col_ntz", sa.DateTime(), nullable=True),
        sa.Column("time_col", sa.Time(), nullable=True),
        sa.Column("uuid_col", sa.Uuid(), nullable=True),
        sa.PrimaryKeyConstraint("bigint_col"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("my_table")
    # ### end Alembic commands ###
